---
- name: Test failed_when
  hosts: ROCKEY
  become: true
  gather_facts: no
  tasks:

  - name: (STEP1) Making sure the /tmp has more then 1gb
    shell: "df -h /tmp | grep -v Filesystem | awk '{print $4}' | cut -d G -f1"
    register: tmpspace
    failed_when: "tmpspace.stdout | float < 1"

  - name: (STEP2) Making sure the Pyhsical Memory more then 2gb
    shell: "cat /proc/meminfo | grep -i memtotal | awk '{print $2/1024/1024}'"
    register: memory
    failed_when: "memory.stdout | float < 2"
